import { Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8fafc' },
  appShell: { flex: 1, backgroundColor: '#f8fafc' },
  topBar: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  appTitle: { fontSize: 22, fontWeight: '800', color: '#0f172a' },
  appSubtitle: { fontSize: 12, color: '#64748b', marginTop: 2 },
  avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#0f172a', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#fff', fontWeight: '800' },
  content: { padding: 16, paddingBottom: 28, gap: 14 },
  heroCard: { backgroundColor: '#0f172a', borderRadius: 20, padding: 18, flexDirection: 'row', alignItems: 'center' },
  eyebrow: { color: '#94a3b8', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 },
  heroTitle: { color: '#fff', fontSize: 24, fontWeight: '800', lineHeight: 30, marginTop: 6 },
  heroSubtitle: { color: '#cbd5e1', fontSize: 13, marginTop: 5, lineHeight: 19 },
  heroEmoji: { fontSize: 42, marginLeft: 8 },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e2e8f0', width: '48.5%' },
  statTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statLabel: { color: '#64748b', fontSize: 11, fontWeight: '700' },
  statIcon: { fontSize: 17 },
  statValue: { color: '#0f172a', fontSize: 21, fontWeight: '800', marginTop: 10 },
  sectionCard: { backgroundColor: '#fff', borderRadius: 18, padding: 14, borderWidth: 1, borderColor: '#e2e8f0' },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  sectionTitle: { color: '#0f172a', fontSize: 17, fontWeight: '800' },
  sectionSubtitle: { color: '#64748b', fontSize: 12, marginTop: 3 },
  actionGrid: { gap: 9 },
  button: { minHeight: 46, borderRadius: 12, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 1, marginTop: 8 },
  primaryButton: { backgroundColor: '#0f172a', borderColor: '#0f172a' },
  secondaryButton: { backgroundColor: '#fff', borderColor: '#cbd5e1' },
  dangerButton: { backgroundColor: '#fff1f2', borderColor: '#fecdd3' },
  disabledButton: { opacity: 0.45 },
  pressedButton: { transform: [{ scale: 0.985 }] },
  buttonText: { fontWeight: '800', fontSize: 13 },
  primaryButtonText: { color: '#fff' },
  secondaryButtonText: { color: '#0f172a' },
  dangerButtonText: { color: '#be123c' },
  disabledButtonText: { color: '#64748b' },
  smallButton: { minHeight: 38, marginTop: 0, paddingHorizontal: 11 },
  warningCard: { backgroundColor: '#fff7ed', borderRadius: 16, borderWidth: 1, borderColor: '#fed7aa', padding: 14 },
  warningTitle: { color: '#9a3412', fontWeight: '800', fontSize: 13 },
  warningText: { color: '#7c2d12', marginTop: 5, fontSize: 12, lineHeight: 18 },
  emptyText: { color: '#64748b', textAlign: 'center', paddingVertical: 18 },
  emptySubtext: { color: '#94a3b8', textAlign: 'center', marginTop: -12, paddingBottom: 18, fontSize: 12 },
  emptyBox: { alignItems: 'center' },
  searchInput: { height: 46, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 12, paddingHorizontal: 12, color: '#0f172a', backgroundColor: '#f8fafc', marginBottom: 10 },
  productCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  productAvatar: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center' },
  productAvatarText: { color: '#334155', fontWeight: '900', fontSize: 17 },
  productInfo: { flex: 1, marginLeft: 10 },
  productName: { color: '#0f172a', fontWeight: '800', fontSize: 14 },
  productMeta: { color: '#64748b', fontSize: 11, marginTop: 4 },
  stockBox: { alignItems: 'flex-end', marginLeft: 8 },
  stockValue: { color: '#15803d', fontSize: 18, fontWeight: '900' },
  lowStockText: { color: '#be123c' },
  stockLabel: { color: '#94a3b8', fontSize: 10 },
  deleteButton: { paddingHorizontal: 8, paddingVertical: 7, marginLeft: 6 },
  deleteText: { color: '#be123c', fontSize: 10, fontWeight: '800' },
  customerCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  customerAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#0f172a', alignItems: 'center', justifyContent: 'center' },
  customerAvatarText: { color: '#fff', fontWeight: '900', fontSize: 17 },
  customerInfo: { flex: 1, marginLeft: 10 },
  customerBalance: { alignItems: 'flex-end' },
  customerAmount: { fontSize: 15, fontWeight: '900' },
  dueText: { color: '#be123c' },
  clearText: { color: '#15803d' },
  customerStatus: { color: '#94a3b8', fontSize: 10, marginTop: 2 },
  transactionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  transactionIcon: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  saleIcon: { backgroundColor: '#dcfce7' },
  purchaseIcon: { backgroundColor: '#fee2e2' },
  paymentIcon: { backgroundColor: '#dbeafe' },
  transactionIconText: { fontSize: 15, fontWeight: '900' },
  transactionInfo: { flex: 1, marginLeft: 10, marginRight: 8 },
  transactionTitle: { color: '#0f172a', fontSize: 12, fontWeight: '800' },
  transactionMeta: { color: '#94a3b8', fontSize: 9, marginTop: 4 },
  transactionAmount: { fontSize: 13, fontWeight: '900' },
  positiveAmount: { color: '#15803d' },
  negativeAmount: { color: '#be123c' },
  profitText: { color: '#15803d', fontSize: 9, fontWeight: '700', marginTop: 3 },
  bottomNav: { height: 72, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#e2e8f0', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingBottom: Platform.OS === 'ios' ? 8 : 2 },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navIcon: { color: '#94a3b8', fontSize: 20, lineHeight: 22 },
  navIconActive: { color: '#0f172a' },
  navLabel: { color: '#94a3b8', fontSize: 9, fontWeight: '700', marginTop: 3 },
  navLabelActive: { color: '#0f172a' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.45)', justifyContent: 'flex-end' },
  modalKeyboard: { width: '100%' },
  modalCard: { backgroundColor: '#fff', maxHeight: '92%', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 18 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  modalTitle: { color: '#0f172a', fontSize: 21, fontWeight: '900' },
  closeButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center' },
  closeButtonText: { fontSize: 23, color: '#475569', lineHeight: 26 },
  modalDescription: { color: '#64748b', fontSize: 12, marginBottom: 15 },
  fieldWrap: { marginBottom: 14 },
  fieldLabel: { color: '#334155', fontSize: 11, fontWeight: '800', marginBottom: 7 },
  input: { height: 48, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 12, paddingHorizontal: 12, color: '#0f172a', backgroundColor: '#f8fafc' },
  chipWrap: { flexDirection: 'row', gap: 8 },
  selectChip: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 11, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#fff' },
  selectChipActive: { backgroundColor: '#0f172a', borderColor: '#0f172a' },
  selectChipText: { color: '#475569', fontSize: 12, fontWeight: '800' },
  selectChipTextActive: { color: '#fff' },
  disabledChip: { opacity: 0.45 },
  optionList: { gap: 8, marginBottom: 10 },
  optionRow: { minHeight: 56, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 11, flexDirection: 'row', alignItems: 'center' },
  optionRowActive: { borderColor: '#0f172a', backgroundColor: '#f8fafc' },
  optionTitle: { color: '#0f172a', fontSize: 13, fontWeight: '800' },
  optionMeta: { color: '#64748b', fontSize: 10, marginTop: 3 },
  check: { color: '#0f172a', fontWeight: '900', fontSize: 18 },
  amountPreview: { backgroundColor: '#f8fafc', borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
  amountPreviewLabel: { color: '#64748b', fontSize: 11, fontWeight: '700' },
  amountPreviewValue: { color: '#0f172a', fontSize: 19, fontWeight: '900' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 4, marginBottom: 4 },
});

export { styles };
