import { StyleSheet } from 'react-native';

const colors = {
  cream: '#F7F1E3',
  ivory: '#FFFDF8',
  charcoal: '#2B2522',
  taupe: '#756B64',
  burgundy: '#6E1428',
  gold: '#C89B3C',
  pyrite: '#C7A96B',
  green: '#3F6B50',
  amber: '#A87524',
  danger: '#8B2638',
  line: '#E8DED0',
  soft: '#F1E9DC',
};

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.cream },
  appShell: { flex: 1, position: 'relative' },
  shellBackground: { ...StyleSheet.absoluteFillObject, backgroundColor: colors.cream },
  appContentLayer: { flex: 1, zIndex: 2 },
  mainContent: { flex: 1, minWidth: 0 },
  manuscriptBackdrop: { ...StyleSheet.absoluteFillObject, overflow: 'hidden', zIndex: 1, elevation: 1 },
  manuscriptFlourish: { position: 'absolute', width: 92, height: 92, opacity: 0.28 },
  manuscriptArc: { position: 'absolute', width: 72, height: 72, borderWidth: 1, borderColor: colors.pyrite, borderRadius: 36, transform: [{ rotate: '18deg' }] },
  manuscriptArcInner: { width: 48, height: 48, top: 12, left: 12, borderRadius: 24, borderColor: colors.burgundy, transform: [{ rotate: '-24deg' }] },
  manuscriptStem: { position: 'absolute', width: 1, height: 68, left: 46, top: 12, backgroundColor: colors.pyrite, transform: [{ rotate: '42deg' }] },
  manuscriptLeaf: { position: 'absolute', width: 15, height: 7, borderWidth: 1, borderColor: colors.pyrite, borderTopLeftRadius: 14, borderBottomRightRadius: 14 },
  manuscriptLeafTop: { left: 34, top: 21, transform: [{ rotate: '-30deg' }] },
  manuscriptLeafBottom: { left: 50, top: 61, transform: [{ rotate: '150deg' }] },
  manuscriptDot: { position: 'absolute', width: 4, height: 4, borderRadius: 2, backgroundColor: colors.gold, left: 43, top: 43 },
  manuscriptTopRight: { top: 142, right: 8, transform: [{ rotate: '14deg' }] },
  manuscriptMiddleLeft: { top: '46%', left: 4, transform: [{ rotate: '-22deg' }] },
  manuscriptBottomRight: { bottom: 22, right: 12, transform: [{ rotate: '38deg' }] },
  manuscriptRuleTop: { position: 'absolute', width: 120, height: 1, top: 132, left: 4, backgroundColor: colors.pyrite, opacity: 0.3, transform: [{ rotate: '-12deg' }] },
  manuscriptRuleBottom: { position: 'absolute', width: 150, height: 1, bottom: 74, right: 4, backgroundColor: colors.burgundy, opacity: 0.22, transform: [{ rotate: '-18deg' }] },
  manuscriptHeaderSprig: { position: 'absolute', top: 14, right: 58, width: 112, height: 116, opacity: 0.26, transform: [{ rotate: '-12deg' }] },
  manuscriptSprigStem: { position: 'absolute', width: 1, height: 106, left: 55, top: 5, backgroundColor: colors.pyrite, transform: [{ rotate: '28deg' }] },
  manuscriptSprigLeaf: { position: 'absolute', width: 25, height: 11, borderWidth: 1, borderColor: colors.pyrite, borderTopLeftRadius: 20, borderBottomRightRadius: 20 },
  manuscriptSprigLeafOne: { left: 42, top: 18, transform: [{ rotate: '-36deg' }] },
  manuscriptSprigLeafTwo: { left: 66, top: 42, transform: [{ rotate: '148deg' }] },
  manuscriptSprigLeafThree: { left: 28, top: 61, transform: [{ rotate: '-30deg' }] },
  manuscriptSprigLeafFour: { left: 54, top: 82, transform: [{ rotate: '148deg' }] },
  manuscriptCompass: { position: 'absolute', top: '61%', right: 28, width: 88, height: 88, opacity: 0.24, alignItems: 'center', justifyContent: 'center' },
  manuscriptCompassRing: { position: 'absolute', width: 82, height: 82, borderWidth: 1, borderColor: colors.pyrite, borderRadius: 41 },
  manuscriptCompassInnerRing: { position: 'absolute', width: 62, height: 62, borderWidth: 1, borderColor: colors.gold, borderRadius: 31 },
  manuscriptCompassNeedleVertical: { position: 'absolute', width: 1, height: 74, backgroundColor: colors.burgundy },
  manuscriptCompassNeedleHorizontal: { position: 'absolute', width: 74, height: 1, backgroundColor: colors.burgundy },
  manuscriptCompassDiamond: { width: 12, height: 12, borderWidth: 1, borderColor: colors.burgundy, transform: [{ rotate: '45deg' }] },
  manuscriptWritingTop: { position: 'absolute', top: 32, left: '24%', opacity: 0.18, transform: [{ rotate: '-5deg' }] },
  manuscriptWritingBottom: { position: 'absolute', bottom: 112, right: 22, opacity: 0.2, transform: [{ rotate: '-8deg' }] },
  manuscriptWritingText: { color: colors.pyrite, fontSize: 16, lineHeight: 23, fontStyle: 'italic', letterSpacing: 0.6 },
  manuscriptMarginalOrnament: { position: 'absolute', top: '53%', left: 8, height: 74, alignItems: 'center', justifyContent: 'space-between', opacity: 0.24 },
  manuscriptMarginalLine: { width: 1, height: 25, backgroundColor: colors.burgundy },
  manuscriptMarginalDiamond: { width: 8, height: 8, borderWidth: 1, borderColor: colors.gold, transform: [{ rotate: '45deg' }] },
  topBar: { position: 'relative', zIndex: 3, elevation: 3, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.ivory, borderBottomWidth: 1, borderBottomColor: colors.line },
  menuButton: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line },
  menuButtonText: { color: colors.burgundy, fontSize: 24, lineHeight: 28, fontWeight: '700' },
  menuPanel: { position: 'absolute', top: 68, right: 16, width: 190, padding: 8, backgroundColor: colors.ivory, borderWidth: 1, borderColor: colors.line, borderRadius: 18, elevation: 8, shadowColor: colors.charcoal, shadowOpacity: 0.14, shadowRadius: 16, shadowOffset: { width: 0, height: 7 } },
  menuItem: { minHeight: 46, borderRadius: 12, justifyContent: 'center', paddingHorizontal: 14, marginVertical: 2 },
  menuItemActive: { backgroundColor: colors.burgundy },
  menuItemText: { color: colors.charcoal, fontSize: 13, fontWeight: '700', letterSpacing: 0.1 },
  menuItemTextActive: { color: colors.ivory },
  appTitle: { fontSize: 22, fontWeight: '900', color: colors.burgundy, letterSpacing: 0.2 },
  appSubtitle: { fontSize: 12, color: colors.taupe, marginTop: 3, letterSpacing: 0.3 },
  avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.burgundy, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.ivory, fontWeight: '800' },
  content: { padding: 18, paddingBottom: 32, gap: 16 },
  searchSection: { backgroundColor: colors.ivory, borderRadius: 16, padding: 12, borderWidth: 1, borderColor: colors.line },
  searchResults: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 5 },
  searchGroup: { marginTop: 5 },
  searchGroupTitle: { color: colors.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.5, paddingVertical: 6 },
  searchResultRow: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.soft, paddingHorizontal: 3 },
  searchResultTitle: { color: colors.charcoal, fontSize: 12, fontWeight: '700', flex: 1 },
  searchResultArrow: { color: colors.burgundy, fontSize: 20, paddingLeft: 8 },
  monthPicker: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  monthButton: { width: 40, height: 36, borderRadius: 11, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' },
  monthButtonText: { color: colors.burgundy, fontSize: 25, lineHeight: 28, fontWeight: '700' },
  monthLabel: { color: colors.charcoal, fontSize: 16, fontWeight: '800', letterSpacing: 0.4 },
  heroCard: { backgroundColor: colors.burgundy, borderRadius: 22, padding: 20, minHeight: 154, flexDirection: 'row', alignItems: 'center', overflow: 'hidden', shadowColor: colors.burgundy, shadowOpacity: 0.2, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 3 },
  eyebrow: { color: '#E9C982', fontSize: 10, fontWeight: '900', letterSpacing: 2.2 },
  heroTitle: { color: colors.ivory, fontSize: 25, fontWeight: '900', lineHeight: 31, marginTop: 8, maxWidth: 270 },
  heroSubtitle: { color: '#F2DCC8', fontSize: 13, marginTop: 7, lineHeight: 19 },
  heroEmoji: { fontSize: 40, marginLeft: 8, opacity: 0.9 },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: { backgroundColor: colors.ivory, borderRadius: 16, padding: 15, borderWidth: 1, borderColor: colors.line, width: '48.5%', minHeight: 92 },
  statTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statLabel: { color: colors.taupe, fontSize: 11, fontWeight: '700' },
  statIcon: { fontSize: 16, color: colors.gold },
  statValue: { color: colors.burgundy, fontSize: 21, fontWeight: '900', marginTop: 11 },
  sectionCard: { backgroundColor: colors.ivory, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: colors.line, shadowColor: colors.charcoal, shadowOpacity: 0.05, shadowRadius: 9, shadowOffset: { width: 0, height: 3 }, elevation: 1 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 13 },
  sectionTitle: { color: colors.charcoal, fontSize: 17, fontWeight: '800', letterSpacing: 0.1 },
  sectionSubtitle: { color: colors.taupe, fontSize: 12, marginTop: 4 },
  actionGrid: { gap: 9 },
  button: { minHeight: 46, borderRadius: 12, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center', borderWidth: 1, marginTop: 8 },
  primaryButton: { backgroundColor: colors.burgundy, borderColor: colors.burgundy },
  secondaryButton: { backgroundColor: colors.ivory, borderColor: '#D6C8B8' },
  dangerButton: { backgroundColor: '#FBF0EE', borderColor: '#E9C6C2' },
  disabledButton: { opacity: 0.45 },
  pressedButton: { transform: [{ scale: 0.985 }], opacity: 0.92 },
  buttonText: { fontWeight: '800', fontSize: 13, letterSpacing: 0.1 },
  primaryButtonText: { color: colors.ivory },
  secondaryButtonText: { color: colors.burgundy },
  dangerButtonText: { color: colors.danger },
  disabledButtonText: { color: colors.taupe },
  smallButton: { minHeight: 38, marginTop: 0, paddingHorizontal: 11 },
  warningCard: { backgroundColor: '#FBF4E6', borderRadius: 16, borderWidth: 1, borderColor: '#E9D2A6', padding: 14 },
  warningTitle: { color: colors.amber, fontWeight: '800', fontSize: 13 },
  warningText: { color: '#80561A', marginTop: 5, fontSize: 12, lineHeight: 18 },
  emptyText: { color: colors.taupe, textAlign: 'center', paddingVertical: 18, fontSize: 13 },
  emptySubtext: { color: '#A49487', textAlign: 'center', marginTop: -12, paddingBottom: 18, fontSize: 12 },
  emptyBox: { alignItems: 'center' },
  searchInput: { height: 46, borderWidth: 1, borderColor: '#D6C8B8', borderRadius: 12, paddingHorizontal: 13, color: colors.charcoal, backgroundColor: '#FCF8F0', marginBottom: 10 },
  productCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderTopWidth: 1, borderTopColor: colors.soft },
  productAvatar: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line },
  productAvatarText: { color: colors.burgundy, fontWeight: '900', fontSize: 17 },
  productInfo: { flex: 1, marginLeft: 11, minWidth: 0 },
  productActions: { alignItems: 'flex-end', marginLeft: 8, gap: 4 },
  productName: { color: colors.charcoal, fontWeight: '800', fontSize: 14 },
  productMeta: { color: colors.taupe, fontSize: 11, marginTop: 4 },
  stockBox: { alignItems: 'flex-end', marginLeft: 8 },
  stockValue: { color: colors.green, fontSize: 18, fontWeight: '900' },
  lowStockText: { color: colors.amber },
  stockLabel: { color: '#A49487', fontSize: 10 },
  deleteButton: { paddingHorizontal: 8, paddingVertical: 7, marginLeft: 6 },
  deleteText: { color: colors.danger, fontSize: 10, fontWeight: '800' },
  addStockButton: { paddingHorizontal: 8, paddingVertical: 7 },
  addStockText: { color: colors.green, fontSize: 10, fontWeight: '900' },
  archiveButton: { paddingHorizontal: 8, paddingVertical: 7 },
  archiveButtonText: { color: colors.taupe, fontSize: 10, fontWeight: '800' },
  recycleButton: { paddingHorizontal: 8, paddingVertical: 7 },
  recycleText: { color: colors.danger, fontSize: 10, fontWeight: '900' },
  archiveCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderTopWidth: 1, borderTopColor: colors.soft },
  recycleCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderTopWidth: 1, borderTopColor: colors.soft },
  recycleRetention: { color: colors.danger, fontSize: 10, fontWeight: '700', marginTop: 4 },
  customerCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, borderTopWidth: 1, borderTopColor: colors.soft },
  customerAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.burgundy, alignItems: 'center', justifyContent: 'center' },
  customerAvatarText: { color: colors.ivory, fontWeight: '900', fontSize: 17 },
  customerInfo: { flex: 1, marginLeft: 10, minWidth: 0 },
  customerBalance: { alignItems: 'flex-end' },
  customerAmount: { fontSize: 15, fontWeight: '900' },
  dueText: { color: colors.danger },
  clearText: { color: colors.green },
  customerStatus: { color: '#A49487', fontSize: 10, marginTop: 2 },
  transactionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderTopWidth: 1, borderTopColor: colors.soft },
  transactionIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  saleIcon: { backgroundColor: '#E8F0E8' },
  purchaseIcon: { backgroundColor: '#F6EBD0' },
  paymentIcon: { backgroundColor: '#F1E0E5' },
  adjustmentIcon: { backgroundColor: '#F6EBD0' },
  transactionIconText: { fontSize: 15, fontWeight: '900', color: colors.burgundy },
  transactionInfo: { flex: 1, marginLeft: 10, marginRight: 8, minWidth: 0 },
  transactionTitle: { color: colors.charcoal, fontSize: 12, fontWeight: '800' },
  transactionMeta: { color: '#A49487', fontSize: 9, marginTop: 4 },
  transactionAmount: { fontSize: 13, fontWeight: '900' },
  positiveAmount: { color: colors.green },
  negativeAmount: { color: colors.danger },
  profitText: { color: colors.green, fontSize: 9, fontWeight: '700', marginTop: 3 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(43,37,34,0.48)', justifyContent: 'flex-end' },
  modalKeyboard: { width: '100%' },
  modalCard: { backgroundColor: colors.ivory, maxHeight: '92%', borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 7 },
  modalTitle: { color: colors.charcoal, fontSize: 21, fontWeight: '900' },
  closeButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' },
  closeButtonText: { fontSize: 23, color: colors.burgundy, lineHeight: 26 },
  modalDescription: { color: colors.taupe, fontSize: 12, marginBottom: 16, lineHeight: 18 },
  fieldWrap: { marginBottom: 14 },
  fieldLabel: { color: colors.charcoal, fontSize: 11, fontWeight: '800', marginBottom: 7, letterSpacing: 0.3 },
  input: { height: 48, borderWidth: 1, borderColor: '#D6C8B8', borderRadius: 12, paddingHorizontal: 13, color: colors.charcoal, backgroundColor: '#FCF8F0' },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  selectChip: { borderWidth: 1, borderColor: '#D6C8B8', borderRadius: 11, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.ivory },
  selectChipActive: { backgroundColor: colors.burgundy, borderColor: colors.burgundy },
  selectChipText: { color: colors.taupe, fontSize: 12, fontWeight: '800' },
  selectChipTextActive: { color: colors.ivory },
  disabledChip: { opacity: 0.45 },
  optionList: { gap: 8, marginBottom: 10 },
  optionRow: { minHeight: 56, borderWidth: 1, borderColor: colors.line, borderRadius: 13, padding: 12, flexDirection: 'row', alignItems: 'center' },
  optionRowActive: { borderColor: colors.burgundy, backgroundColor: '#FBF3F0' },
  optionTitle: { color: colors.charcoal, fontSize: 13, fontWeight: '800' },
  optionMeta: { color: colors.taupe, fontSize: 10, marginTop: 3 },
  check: { color: colors.burgundy, fontWeight: '900', fontSize: 18 },
  amountPreview: { backgroundColor: colors.soft, borderRadius: 14, padding: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 7 },
  amountPreviewLabel: { color: colors.taupe, fontSize: 11, fontWeight: '700' },
  amountPreviewValue: { color: colors.burgundy, fontSize: 19, fontWeight: '900' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 4, marginBottom: 4 },
  reportInsight: { color: colors.charcoal, fontSize: 13, lineHeight: 21, paddingVertical: 3 },
  reportHeading: { color: colors.burgundy, fontWeight: '800', fontSize: 12, marginTop: 10, marginBottom: 4 },
  reportLine: { color: colors.taupe, fontSize: 12, paddingVertical: 5, borderTopWidth: 1, borderTopColor: colors.soft },
  collectionCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderTopWidth: 1, borderTopColor: colors.soft },
  collectionDue: { color: colors.danger, fontSize: 11, fontWeight: '800', marginTop: 4 },
  startupScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cream, padding: 24 },
  startupMark: { minWidth: 190, height: 72, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.burgundy, marginBottom: 18, paddingHorizontal: 20, borderWidth: 1, borderColor: colors.gold },
  startupMarkText: { color: colors.ivory, fontSize: 30, fontWeight: '900', letterSpacing: 0.8 },
  startupTitle: { color: colors.burgundy, fontSize: 28, fontWeight: '900', letterSpacing: 0.3 },
  startupSubtitle: { color: colors.taupe, fontSize: 13, marginTop: 8 },
  startupRule: { width: 74, height: 2, backgroundColor: colors.gold, marginTop: 15, opacity: 0.75 },
  startupError: { color: colors.danger, fontSize: 12, lineHeight: 18, marginTop: 16, maxWidth: 300, textAlign: 'center' },
});

export { styles };
